name: Java CI

on:
  push:
    branches: [ghactions]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Validate, compile, and test
        run: mvn -f ../../pom.xml verify

      - name: Run Checkstyle
        run: mvn -f ../../pom.xml verify
