name: Java CI - Deliver

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Validate, compile, and test
        run: mvn verify

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Package the application
        run: mvn package

      - name: Upload .jar file
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar
